/* Generated by SVG Vibe Studio owner tool. */
window.SVG_VIBE_DONATIONS = {
  "version": 1,
  "methods": [
    {
      "type": "crypto",
      "name": "Sol",
      "icon": ""https://raw.githubusercontent.com/spoilpetal/spoilpetal.github.io/main/svg-vibe-studio/assets/solana.png",
      "note": "Only send Solana (SOL) assets to this address. Other assets will be lost forever.",
      "enabled": true,
      "address": "92QPKoHSZRTa9k9kUXfXbbKm9TsSxHF1P6xH7xdbndYi"
    },
    {
      "type": "crypto",
      "name": "Btc",
      "icon": "https://raw.githubusercontent.com/spoilpetal/spoilpetal.github.io/main/svg-vibe-studio/assets/bitcoin.png",
      "note": "Only send Bitcoin (BTC) assets to this address. Other assets will be lost forever.",
      "enabled": true,
      "address": "bc1qme5qs2a29383nx9d0s470lfn5uaq2npwuvexr3"
    },
    {
      "type": "crypto",
      "name": "Tron",
      "icon": "https://raw.githubusercontent.com/spoilpetal/spoilpetal.github.io/main/svg-vibe-studio/assets/tron.png",
      "note": "Only send Tron (TRX) assets to this address. Other assets will be lost forever.",
      "enabled": true,
      "address": "TLzPfTJoonWZWAGeeKy47g3r6nP5ciejFF"
    },
    {
      "type": "crypto",
      "name": "Base",
      "icon": "https://raw.githubusercontent.com/spoilpetal/spoilpetal.github.io/main/svg-vibe-studio/assets/base.png",
      "note": "Only send Base (ETH) assets to this address. Other assets will be lost forever.",
      "enabled": true,
      "address": "0x1a1296165BF8d53145edf23C86EeAf9e7E52710a"
    },
    {
      "type": "crypto",
      "name": "Eth",
      "icon": "https://raw.githubusercontent.com/spoilpetal/spoilpetal.github.io/main/svg-vibe-studio/assets/ethereum.png",
      "note": "Only send Ethereum (ETH) assets to this address. Other assets will be lost forever.",
      "enabled": true,
      "address": "0x1a1296165BF8d53145edf23C86EeAf9e7E52710a"
    },
    {
      "type": "crypto",
      "name": "Bnb",
      "icon": "https://raw.githubusercontent.com/spoilpetal/spoilpetal.github.io/main/svg-vibe-studio/assets/binance.png",
      "note": "Only send BNB Smart Chain (BNB) assets to this address. Other assets will be lost forever.",
      "enabled": true,
      "address": "0x1a1296165BF8d53145edf23C86EeAf9e7E52710a"
    },
    {
      "type": "crypto",
      "name": "xvg",
      "icon": "https://raw.githubusercontent.com/spoilpetal/spoilpetal.github.io/main/svg-vibe-studio/assets/xvg.png",
      "note": "https://vergecurrency.com/ (verge)",
      "enabled": true,
      "address": "DNMjjR7HtcfrDetKXJQ7xtKSZKjANPKLiq"
    },
    {
      "type": "crypto",
      "name": "xmr",
      "icon": "https://raw.githubusercontent.com/spoilpetal/spoilpetal.github.io/main/svg-vibe-studio/assets/monero.png",
      "note": "Monero",
      "enabled": true,
      "address": "86MRJQZeQdX6Nx1kuYSAn3fEKTrXusr6m1nnS93gTF4AJYvoKoEsJfWNr4P5PbigzENnZaqpo5buMXjHwbUDVFZcPTQ9fRF"
    }
  ]
};
